### ISSUE TITLE
关于Epoch的问题

### ISSUE THREAD

**Issue by RanKoala** [xiaoqiang-lu/WSCL#1]
作者你好，非常感谢你的论文和代码开源，在阅读你的论文后，我有个关于Epoch的问题，希望能得到你的解惑：
        监督学习和半监督学习过程中的Epoch是否一致？如果不一致，又具体是如何确定的？在我进行SSL试验过程中，在数据增强正确的前提下，通过提高监督学习的Epoch数目，是能够有效提高精度的。所以希望知道你是怎么考虑这个问题的？

**Comment by xiaoqiang-lu** [comment]
你好读者，通常基于自训练的方法，需要先进行监督学习得到教师模型，再进行半监督学习进行知识传授，是一种分阶段的训练过程，常规做法是两个阶段训练的epoch数相同。而本文是基于一致性学习的一种框架，通常这类方法是同步进行监督学习以及半监督学习，即端到端训练。举个例子，假设现在具有100张标记图像以及900张无标记图像，首先需要将100张标记图像复制成与无标记图像数量相同，即900张标记图像。然后这900张标记图像再和900张无标记图像一同参与训练。

**Comment by RanKoala** [comment]
非常感谢你的耐心解答，你对两种SSL学习的训练过程进行了详细的解释，非常感谢。
但可能我没有表达出我正确的意思。我更想知道的是在对比试验过程中，与SSL进行对比的普通监督学习是如何进行训练的？比如基于一致性正则化的训练过程中，只有100张有标记图像，那使用这100张有标记图像进行普通监督学习是如何进行的呢？训练Epoch又如何确定的呢？
目前我自己的做法是100张有标记图像的训练轮次是根据训练Loss曲线来确定的，在曲线收敛不再下降且未出现过拟合的前提下进行停止。而SSL学习过程中，由于数据量的增大，训练Epoch与监督学习是不一样的。且SSL过程中，一个Epoch会对100张有标记数据进行多次重复学习（跟你上述讲的复制到相同数量同样意思）。

**Comment by xiaoqiang-lu** [comment]
通常大家对于监督基线的做法都是常规的监督学习，保持训练epoch数和半监督学习相同，例如都进行100个epoch，然后取各自最佳性能进行比较。尽管对于不同数量的标记数据进行监督学习所需要的epoch数不尽相同，但都默认设置为一样的进行比较。

**Comment by RanKoala** [comment]
好的，谢谢你的耐心解答。
